name: CMake with Multiple Python Versions (MSVC)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.11.9" ]

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31'

      - name: Configure project with CMake (MSVC)
        run: |
          cmake -S . -B build ^
            -G "Visual Studio 17 2022" ^
            -A x64 ^
            -DPython3_EXECUTABLE=%pythonLocation%\python.exe

      - name: Build project (MSVC)
        run: cmake --build build --config Release
        
      - name: Upload .pyd artifact
        uses: actions/upload-artifact@v4
        with:
          name: havokpy-${{ matrix.python-version }}.pyd
          path: build/Release/*.pyd
